import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const langs=['en','es','ja','zh-hans','zh-hant','pt-br','fr','de','ar'];
const names={en:'English',es:'Español',ja:'日本語','zh-hans':'简体中文','zh-hant':'繁體中文','pt-br':'Português (Brasil)',fr:'Français',de:'Deutsch',ar:'العربية',und:'—'};
const tags={en:'en',es:'es',ja:'ja','zh-hans':'zh-Hans','zh-hant':'zh-Hant','pt-br':'pt-BR',fr:'fr',de:'de',ar:'ar'};
const origin='https://preferencecompass.info',version='1.2.0',out=path.join(root,'dist');
const cssText=fs.readFileSync(path.join(root,'src/styles.css'),'utf8');
const cssAsset='styles-'+createHash('sha256').update(cssText).digest('hex').slice(0,12)+'.css';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prose=(s,lang)=>lang==='ar'?String(s).split(/(https?:\/\/[^\s]+|alpha\/\(alpha\+beta\)|(?:alpha|beta)=\d+|belief=null|Beta–Bernoulli|Preference Compass|Deshimaru Sakaguchi|Markdown|JSON|JavaScript|\bX\b)/g).map((part,i)=>i%2?'<bdi dir="ltr">'+esc(part)+'</bdi>':esc(part)).join(''):esc(s);
const bank={},ui={},docs={};for(const lang of langs){bank[lang]=read('src/locales/'+lang+'.json');ui[lang]=read('src/locales/'+lang+'.ui.json');docs[lang]=read('src/locales/'+lang+'.docs.json');}
const flat=bank.en.flatMap(c=>c.questions);
for(const lang of langs){const b=bank[lang],f=b.flatMap(c=>c.questions);if(b.length!==10||f.length!==100||new Set(f.map(q=>q.id)).size!==100)throw Error('Invalid question count: '+lang);f.forEach((q,i)=>{if(q.id!==flat[i].id||!q.text||q.options.length!==4||q.options.some((o,j)=>o.id!==flat[i].options[j].id||!o.label))throw Error('Question alignment: '+lang+' '+i);});if(Object.keys(ui[lang]).sort().join()!=Object.keys(ui.en).sort().join()||Object.values(ui[lang]).some(s=>!s))throw Error('UI mismatch: '+lang);for(const k of ['about','guide','numerical','privacy','usage'])if(docs[lang][k].length!==docs.en[k].length)throw Error('Document mismatch: '+lang);}
const schema=read('src/schema.json'),protocol=read('src/protocol.json');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(out,p)),{recursive:true});fs.writeFileSync(path.join(out,p),s);};
const url=(lang,suffix='')=>origin+'/'+lang+'/'+suffix;
const alternates=suffix=>langs.map(l=>'<link rel="alternate" hreflang="'+tags[l]+'" href="'+url(l,suffix)+'">').join('\n')+'\n<link rel="alternate" hreflang="x-default" href="'+url('en',suffix)+'">';
function header(lang,title,suffix=''){const u=ui[lang];return '<!doctype html>\n<html lang="'+tags[lang]+'" dir="'+(lang==='ar'?'rtl':'ltr')+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+esc(title)+' · Preference Compass</title><meta name="description" content="'+esc(u.intro)+'"><meta name="theme-color" content="#10192d"><link rel="canonical" href="'+url(lang,suffix)+'">'+alternates(suffix)+'<meta property="og:title" content="'+esc(title)+' · Preference Compass"><meta property="og:description" content="'+esc(u.intro)+'"><meta property="og:url" content="'+url(lang,suffix)+'"><meta property="og:type" content="website"><meta name="twitter:card" content="summary"><meta name="twitter:creator" content="@Deshimaru_S"><link rel="stylesheet" href="/assets/'+cssAsset+'"></head><body><div class="ambient" aria-hidden="true"></div><header class="topbar"><a dir="ltr" class="brand" href="/'+lang+'/"><span class="brand-mark" aria-hidden="true">C</span><span><strong>Preference Compass</strong><small>RELATIONSHIP PORTABILITY</small></span></a><nav class="languages" aria-label="'+esc(u.language)+'">'+langs.map(l=>'<a data-language-link href="/'+l+'/'+suffix+'" lang="'+tags[l]+'" hreflang="'+tags[l]+'" dir="'+(l==='ar'?'rtl':'ltr')+'"'+(l===lang?' aria-current="page"':'')+'>'+names[l]+'</a>').join('')+'</nav><a class="guide-entry" href="/'+lang+'/guide/">'+esc(docs[lang].quickstart.title)+'</a></header>';}
function footer(lang){const u=ui[lang];return '<footer class="site-footer"><nav aria-label="'+esc(u.guide)+'">'+[['',u.openQuestionnaire],['about/',u.about],['guide/',u.guide],['questions/',u.questions],['privacy/',u.privacy],['terms/',u.terms]].map(([p,label])=>'<a href="/'+lang+'/'+p+'">'+esc(label)+'</a>').join(' · ')+' · <a href="/spec/relationship-portability-1.1.2.schema.json">'+esc(u.schema)+'</a></nav><p>'+esc(u.author)+' <a dir="ltr" rel="author" href="https://deshimarusakaguchi.com/">Deshimaru Sakaguchi</a> · <a dir="ltr" href="https://x.com/Deshimaru_S">X: @Deshimaru_S</a> · <a href="https://github.com/sana-os/PreferenceCompass">'+esc(u.source)+'</a></p><p class="meta">'+esc(u.experimental)+' · v'+version+'</p></footer>'}
const selectOptions=(lang,unknown=true)=>Object.entries(names).filter(([l])=>unknown||l!=='und').map(([l,n])=>'<option value="'+l+'"'+(l===lang?' selected':'')+'>'+n+'</option>').join('');
function questionnaire(lang){const u=ui[lang],q=bank[lang][0].questions[0];return header(lang,u.openQuestionnaire)+`<noscript><p class="notice">${esc(u.noJs)}</p></noscript><p class="notice" id="appError">${esc(u.loadError)}</p>
<main class="shell"><aside class="rail"><div class="rail-progress"><div class="progress-label"><span>${esc(u.progress)}</span><strong id="progressCount" dir="ltr">0 / 100</strong></div><div id="progressTrack" class="progress-track" role="progressbar" aria-label="${esc(u.progress)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span id="progressBar"></span></div></div><p class="tool-explainer">${esc(u.intro)}</p><nav id="categoryNav" aria-label="${esc(u.questions)}">${bank[lang].map(c=>'<span>'+esc(c.name)+'</span>').join('')}</nav><button class="review-link" id="reviewLink" type="button">${esc(u.review)} ${lang==='ar'?'←':'→'}</button><p class="meta">${esc(u.local)}</p><button class="secondary-button" id="resetButton" type="button">${esc(u.reset)}</button></aside>
<section class="workspace" id="questionView"><div class="context-row"><span class="eyebrow" id="categoryLabel">${esc(bank[lang][0].name)}</span><span class="question-position" id="questionPosition">1 / 100</span></div><div class="question-card"><p class="why" id="categoryHint">${esc(bank[lang][0].hint)}</p><h1 tabindex="-1" id="questionText">${esc(q.text)}</h1><p class="instruction">${esc(u.instruction)}</p><fieldset class="options" id="options"><legend>${esc(u.choices)}</legend></fieldset><label class="free-answer" for="responseStatus">${esc(u.status)}</label><select id="responseStatus">${['unanswered','answered','unknown','context_dependent','not_applicable','declined'].map(s=>'<option value="'+s+'">'+esc(u[s])+'</option>').join('')}</select><label class="free-answer" for="freeText"><span>${esc(u.note)} <small>${esc(u.optional)}</small></span></label><textarea dir="auto" id="freeText" rows="3" maxlength="500" placeholder="${esc(u.placeholder)}"></textarea><p class="meta" dir="ltr"><span id="charCount">0</span> / 500</p><label class="meta" for="noteLanguage">${esc(u.noteLanguage)}</label><select id="noteLanguage">${selectOptions(lang)}</select></div><div class="question-actions"><button class="secondary-button" id="prevButton" type="button">${lang==='ar'?'→':'←'} ${esc(u.previous)}</button><button class="skip-button" id="skipButton" type="button">${esc(u.later)}</button><button class="primary-button" id="nextButton" type="button">${esc(u.next)} ${lang==='ar'?'←':'→'}</button></div><p class="key-hint">${esc(u.keyboard)}</p></section>
<section class="workspace review-view" id="reviewView" hidden><div class="context-row"><span class="eyebrow">${esc(u.review)}</span><span id="reviewCompletion" dir="ltr"></span></div><div class="review-header"><div><h1 id="reviewTitle" tabindex="-1">${esc(u.reviewTitle)}</h1><p>${esc(u.reviewIntro)}</p></div><button class="secondary-button" id="backToQuestions" type="button">${esc(u.back)}</button></div><p id="unansweredSummary"></p><button class="secondary-button" id="firstUnanswered" type="button">${esc(u.first)}</button><div id="reviewList"></div><article class="review-panel accent-panel"><h2>${esc(u.exportTitle)}</h2><p>${esc(u.exportIntro)}</p><div class="export-actions"><button class="primary-button" id="downloadMarkdown" disabled type="button">${esc(u.saveMd)}</button><button class="secondary-button" id="downloadJson" disabled type="button">${esc(u.saveJson)}</button></div></article><details class="usage-note"><summary>${esc(u.handoff)}</summary><p id="handoffText">${esc(docs[lang].handoff)}</p><button class="secondary-button" id="copyHandoff" type="button">${esc(u.copy)}</button><p><a href="/${lang}/guide/">${esc(u.guide)}</a></p></details></section></main>
${footer(lang)}<dialog id="resetDialog" aria-labelledby="resetTitle"><form method="dialog"><h2 id="resetTitle">${esc(u.resetTitle)}</h2><p>${esc(u.resetBody)}</p><div class="dialog-actions"><button class="secondary-button" value="cancel">${esc(u.cancel)}</button><button class="danger-button" id="confirmReset" value="confirm">${esc(u.delete)}</button></div></form></dialog><div id="toast" class="toast" role="status" aria-live="polite"></div><script defer src="/assets/questions.js"></script><script defer src="/assets/data-${lang}.js"></script><script defer src="/assets/core.js"></script><script defer src="/assets/app.js"></script></body></html>`;}
const mdLinks=lang=>`[${ui[lang].openQuestionnaire}](${url(lang)}) · [${ui[lang].guide}](${url(lang,'guide/')}) · [${ui[lang].source}](https://github.com/sana-os/PreferenceCompass)`;
function docPage(lang,kind,sections){const title=sections[0][0],suffix=kind+'/';let html=header(lang,title,suffix)+'<main class="document"><h1>'+esc(title)+'</h1>';let md='# '+title+'\n\n';if(kind==='guide'){const q=docs[lang].quickstart;html+='<section class="quickstart"><h2>'+esc(q.title)+'</h2><ol>'+q.steps.map(([title,text])=>'<li><h3>'+esc(title.replace(/^\d+\. /,''))+'</h3><p>'+prose(text,lang)+'</p></li>').join('')+'</ol><h3>'+esc(q.promptTitle)+'</h3><blockquote>'+prose(q.prompt,lang)+'</blockquote><p><a class="guide-return" href="/'+lang+'/">'+esc(q.returnLabel)+'</a></p></section>';md+='## '+q.title+'\n\n'+q.steps.map(([title,text])=>'### '+title+'\n\n'+text).join('\n\n')+'\n\n### '+q.promptTitle+'\n\n'+q.prompt+'\n\n';}sections.forEach((s,i)=>{if(i){html+='<h2>'+esc(s[0])+'</h2>';md+='## '+s[0]+'\n\n';}for(const p of s.slice(1)){html+='<p>'+prose(p,lang)+'</p>';md+=p+'\n\n';}});if(kind==='guide'){html+='<h2>'+esc(ui[lang].handoff)+'</h2><blockquote>'+prose(docs[lang].handoff,lang)+'</blockquote>';md+='## '+ui[lang].handoff+'\n\n'+docs[lang].handoff+'\n\n';}html+='<p><a href="/'+lang+'/'+kind+'.md">Markdown</a></p></main>'+footer(lang)+'</body></html>';md+=mdLinks(lang)+'\n\nDeshimaru Sakaguchi — https://deshimarusakaguchi.com/\n\n'+ui[lang].experimental+'\n';write(lang+'/'+suffix+'index.html',html);write(lang+'/'+kind+'.md',md);}
write('assets/'+cssAsset,cssText);
write('assets/questions.js','window.PC_QUESTIONS='+JSON.stringify(bank)+';\n');
for(const file of ['app.js','core.js','styles.css'])write('assets/'+file,fs.readFileSync(path.join(root,'src',file),'utf8'));
for(const lang of langs){const data={language:lang,ui:ui[lang],docs:docs[lang],schema,protocol,termsEnglish:docs.en.usage.slice(1).join('\n\n')};write('assets/data-'+lang+'.js','window.PC_DATA='+JSON.stringify(data)+';\n');write(lang+'/index.html',questionnaire(lang));write(lang+'/index.md','# Preference Compass\n\n'+docs[lang].about.slice(1).join('\n\n')+'\n\n'+mdLinks(lang)+'\n');docPage(lang,'about',[docs[lang].about]);docPage(lang,'guide',[docs[lang].guide,docs[lang].numerical]);docPage(lang,'privacy',[docs[lang].privacy]);docPage(lang,'terms',[docs[lang].usage]);
 let md='# '+ui[lang].questions+'\n\nQuestionnaire: preference-compass-100 / 2.0.0; translation: 1.0.0; '+lang+'\n\n'+ui[lang].instruction+'\n\n'+['unknown','context_dependent','not_applicable','declined'].map(s=>s+': '+ui[lang][s]).join('\n\n')+'\n\n';
 let html=header(lang,ui[lang].questions,'questions/')+'<main class="document"><h1>'+esc(ui[lang].questions)+'</h1><p>'+esc(ui[lang].instruction)+'</p>';
 for(const c of bank[lang]){md+='## '+c.name+'\n\n';html+='<h2>'+esc(c.name)+'</h2>';for(const q of c.questions){md+='### '+q.id+' — '+q.text+'\n\n'+q.options.map(o=>'- '+o.id+': '+o.label).join('\n')+'\n\n';html+='<article><h3><bdi dir="ltr">'+esc(q.id)+'</bdi> — '+esc(q.text)+'</h3><ol>'+q.options.map(o=>'<li>'+esc(o.label)+'</li>').join('')+'</ol></article>';}}
 write(lang+'/questions.md',md+mdLinks(lang)+'\n');write(lang+'/questions/index.html',html+'<p><a href="/'+lang+'/questions.md">Markdown</a> · <a href="/data/questionnaires/'+lang+'.json">JSON</a></p></main>'+footer(lang)+'</body></html>');
 write('data/questionnaires/'+lang+'.json',JSON.stringify({id:'preference-compass-100',version:'2.0.0',translationVersion:'1.0.0',language:lang,categories:bank[lang]},null,2)+'\n');
}
write('index.html',questionnaire('en'));write('index.md',fs.readFileSync(path.join(out,'en/index.md'),'utf8'));
write('404.html',header('en','Page not found')+'<main class="document"><h1>404</h1><p><a href="/en/">Preference Compass</a></p></main>'+footer('en')+'</body></html>');
write('spec/relationship-portability-1.1.2.schema.json',JSON.stringify(schema,null,2)+'\n');write('spec/handling-protocol-1.1.0.json',JSON.stringify(protocol,null,2)+'\n');
let protocolMd='# Relationship Portability Protocol 1.1.0\n\nCanonical reference: English.\n\n';for(const [k,v]of Object.entries(protocol)){protocolMd+='## '+k+'\n\n'+(typeof v==='string'?v:Array.isArray(v)?v.map(x=>'- '+x).join('\n'):Object.entries(v).map(([a,b])=>'- **'+a+'**: '+b).join('\n'))+'\n\n';}write('spec/handling-protocol-1.1.0.md',protocolMd);
write('AI-USE.md','# Automated access and AI use\n\nPublic source code, questionnaire text, translations, schemas and documentation may be indexed, retrieved, analyzed and used for AI training. No AI crawler is intentionally excluded by this project. Preserve provenance when republishing or building a derivative under the [use and attribution terms](https://preferencecompass.info/en/terms/).\n\nThis permission does not grant access to anyone’s private questionnaire answers or relationship sheets. The site does not publish those answers. robots.txt is crawl guidance, not an access-control mechanism.\n\nCreator: [Deshimaru Sakaguchi](https://deshimarusakaguchi.com/).\n');
write('robots.txt','User-agent: *\nAllow: /\n\nSitemap: '+origin+'/sitemap.xml\n');
write('llms.txt','# Preference Compass\n\n> An experiment in user-owned relationship portability across AI sessions and platforms, by Deshimaru Sakaguchi.\n\nQuestionnaires provide initial observations, not personality scores or established trust. Complete initial responses are required, including unknown or declined. Dialogue-updated sheets have no fixed item count. Transfer the complete schema, handling protocol and current relationship data; task progress is excluded.\n\n## Author and public use\n\n- [Deshimaru Sakaguchi](https://deshimarusakaguchi.com/)\n- [AI use policy]('+origin+'/AI-USE.md): Indexing, retrieval and AI training on public materials are permitted; private answers are not public.\n- [Use and attribution]('+origin+'/en/terms.md)\n\n## Canonical specifications\n\n- [Handling protocol]('+origin+'/spec/handling-protocol-1.1.0.md)\n- [Machine protocol]('+origin+'/spec/handling-protocol-1.1.0.json)\n- [JSON Schema]('+origin+'/spec/relationship-portability-1.1.2.schema.json)\n\n## Languages\n\n'+langs.map(l=>'- ['+names[l]+']('+url(l,'index.md')+')\n- ['+names[l]+' — handling guide]('+url(l,'guide.md')+')\n- ['+names[l]+' — questions]('+url(l,'questions.md')+')').join('\n')+'\n');
const routes=['','about/','guide/','questions/','privacy/','terms/'];
const locs=langs.flatMap(l=>routes.map(r=>({l,r})));
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'+locs.map(({l,r})=>'<url><loc>'+url(l,r)+'</loc>'+langs.map(a=>'<xhtml:link rel="alternate" hreflang="'+tags[a]+'" href="'+url(a,r)+'"/>').join('')+'<xhtml:link rel="alternate" hreflang="x-default" href="'+url('en',r)+'"/></url>').join('\n')+'\n</urlset>\n');
write('_redirects','/ /en/ 302\n');
write('_headers',`/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()
  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'
  Cache-Control: public, max-age=0, must-revalidate
/*.md
  Content-Type: text/markdown; charset=utf-8
/robots.txt
  Content-Type: text/plain; charset=utf-8
/llms.txt
  Content-Type: text/plain; charset=utf-8
/sitemap.xml
  Content-Type: application/xml; charset=utf-8
`);
write('release.json',JSON.stringify({release:version,domain:origin,questionnaireVersion:'2.0.0',translationVersion:'1.0.0',schemaVersion:'1.1.2',protocolVersion:'1.1.0',languages:langs,translationReview:'AI-assisted translations; independent native-speaker validation pending.',source:'https://github.com/sana-os/PreferenceCompass'},null,2)+'\n');
console.log('Built '+langs.length+' language/script editions × 100 questions; '+locs.length+' localized HTML routes.');

write('spec/relationship-portability-1.1.0.schema.json',fs.readFileSync(path.join(root,'src/legacy/relationship-portability-1.1.0.schema.json'),'utf8'));

write('spec/relationship-portability-1.1.1.schema.json',fs.readFileSync(path.join(root,'src/legacy/relationship-portability-1.1.1.schema.json'),'utf8'));
